### ISSUE TITLE
Logfil genererar inget från första genereringen

### ISSUE THREAD

**Issue by Pontus-Nygren** [JoForsberg/datagen#10]
Programmet genererar en text direkt när du startar det men den texten syns ej i logfilen som man får 
från "Print logs to File".

Om man startar programmet och kryssar i checkboxen Print logs to file med den första genererade texten
som kommer när man startar programmet så existerar texten inte i loggen sen

Allvarlighetsgrad - Ej allvarlig.

**Comment by JoForsberg** [comment]
Detta är en feature då det är en default sträng som finns. Programmet ska generera i loggen efter aktivitet som du själv gjort.
