### ISSUE TITLE
Program hänger sig vid för högt length of string värde

### ISSUE THREAD

**Issue by Pontus-Nygren** [JoForsberg/datagen#2]
Programmet hänger sig om man anger ett högt värde, t.ex 1000000 och använder sig av någon av generate knapparna.

För att återskapa
1. Sätt Lenght of string till 10000000
2. klicka på GenerateString, Generate Random Email eller Generate a counterstring.
3. Förväntat resultat borde vara något generat efter värdet eller en varning / felhantering att stoppa det innan det hänger.

Allvarlighetsgrad - Ej så allvarligt då man sällan genererar så mycket text.
Testat på Windows 8.1

**Comment by magnusnorlin** [comment]
Samma på Win10

**Comment by christofferflystam** [comment]
Min dator gjorde 1000000 på 6 min. Så Programmet hänger sig inte, men det är en bugg att man som användare inte får reda på att det jobbar på en sträng. Kör Windows 10 Home (Version 1703)

**Comment by JoForsberg** [comment]
Stänger issuen då programmet inte krashar.
