### ISSUE TITLE
ASCII Tavlan visar okorrekta tecken

### ISSUE THREAD

**Issue by ConradLetelier** [JoForsberg/datagen#20]
Buggen anses som "inte allvarlig" eftersom programet inte tar skada/crashar av buggen.

Buggen uppstår när man genererar ASCII tavlan.

![test](https://user-images.githubusercontent.com/23025098/29667395-92bd4a6c-88dc-11e7-90e3-476e236820a9.jpg)

Korrekt ASCII tabell finns att hitta [här](http://www.asciitable.com/)

EDIT: Det funkar att pasta den genererade tabellen från clipboard i ett textdokument, buggen visas alltså endast i Datagens textarea

Test skapat i Windows 10 Enterprise

**Comment by JoForsberg** [comment]
Vad händer om du copy/paste den genererade texten in i ett textfält eller ett textdokument?

**Comment by ConradLetelier** [comment]
Det funkar att pasta den genererade tabellen från clipboard i ett textdokument, buggen visas alltså endast i Datagens textarea

**Comment by JoForsberg** [comment]
Stänger pga att det fungerar för användarens ändamål.
