### ISSUE TITLE
programmet kraschar vid för stort antal karaktärer 

### ISSUE THREAD

**Issue by annafock** [JoForsberg/datagen#21]

**Comment by annafock** [comment]
![skarmavbild 2017-08-24 kl 14 57 08](https://user-images.githubusercontent.com/18632351/29667423-ab61f270-88dc-11e7-9f29-b7f2a65bb166.png)

**Comment by annafock** [comment]
Fel, det kraschar inte, det tar bara längre tid att generera bokstäverna.

**Comment by JoForsberg** [comment]
Så det är inget fel egentligen, eller?

**Comment by annafock** [comment]
Nä, exakt. Det kanske skulle vara bra att tydliggöra på något sätt att programmet arbetar, istället för att knappen blir blå och programmet fryser.

**Comment by JoForsberg** [comment]
Stänger issuen då det inte är ett fel längre.
