### ISSUE TITLE
Checkbox International Characters har ingen label vid mouse float.

### ISSUE THREAD

**Issue by magnusnorlin** [JoForsberg/datagen#24]
Ingen förklarande label kommer fram när man hovrar mupekare över checkbox och text International Characters.

Uppträder alltid. Användare förväntar sig en label med förklaring av vad checkboxen medför.

Inte så allvarlig. Checkboxen har ändå ingen funktion.

v1.0, Win 10

**Comment by JoForsberg** [comment]
Duplicate. Stänger issuen. Uppdatera gärna den gamla issuen.
